name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@docs-vuepress

    - name: Build and Deploy
      uses: agritheory/forten@docs-vuepress
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        BUILD_DIR: docs/.vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build