name: Deploy to GitHub pages
on:
  push:
    branches: [ docs-vuepress ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: agritheory/forten@docs-vuepress
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: agritheory/forten
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm docs:build
        BUILD_DIR: docs/.vuepress/dist/