name: Deploy to GitHub pages
on:
  push:
    branches: [ docs-vuepress ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: forten
      uses: agritheory/forten@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: agritheory/forten
        TARGET_BRANCH: docs-vuepress
        BUILD_SCRIPT: npm docs:build
        BUILD_DIR: docs/.vuepress/dist/