name: Deploy to GitHub pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@docs-vuepress

    - name: Build
      uses: agritheory/forten@docs-vuepress
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/